export const ADMIN_ABSTRACT_REQUEST = 'ADMIN_ABSTRACT_REQUEST'
export const ADMIN_ABSTRACT_SUCCESS = 'ADMIN_ABSTRACT_SUCCESS'
export const ADMIN_ABSTRACT_FAIL = 'ADMIN_ABSTRACT_FAIL'

export const USER_ABSTRACT_REQUEST = 'USER_ABSTRACT_REQUEST'
export const USER_ABSTRACT_SUCCESS = 'USER_ABSTRACT_SUCCESS'
export const USER_ABSTRACT_FAIL = 'USER_ABSTRACT_FAIL'

export const UPDATE_ABSTRACT_REQUEST = 'UPDATE_ABSTRACT_REQUEST'
export const UPDATE_ABSTRACT_SUCCESS = 'UPDATE_ABSTRACT_SUCCESS'
export const UPDATE_ABSTRACT_RESET = 'UPDATE_ABSTRACT_RESET'
export const UPDATE_ABSTRACT_FAIL = 'UPDATE_ABSTRACT_FAIL'

export const DELETE_ABSTRACT_REQUEST = 'DELETE_ABSTRACT_REQUEST'
export const DELETE_ABSTRACT_SUCCESS = 'DELETE_ABSTRACT_SUCCESS'
export const DELETE_ABSTRACT_RESET = 'DELETE_ABSTRACT_RESET'
export const DELETE_ABSTRACT_FAIL = 'DELETE_ABSTRACT_FAIL'

export const NEW_ABSTRACT_REQUEST = 'NEW_ABSTRACT_REQUEST'
export const NEW_ABSTRACT_SUCCESS = 'NEW_ABSTRACT_SUCCESS'
export const NEW_ABSTRACT_RESET = 'NEW_ABSTRACT_RESET'
export const NEW_ABSTRACT_FAIL = 'NEW_ABSTRACT_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'