export const ALL_ARTICLES_REQUEST = 'ALL_ARTICLES_REQUEST'
export const ALL_ARTICLES_SUCCESS = 'ALL_ARTICLES_SUCCESS'
export const ALL_ARTICLES_FAIL = 'ALL_ARTICLES_FAIL'

export const ADMIN_ARTICLES_REQUEST = 'ADMIN_ARTICLES_REQUEST'
export const ADMIN_ARTICLES_SUCCESS = 'ADMIN_ARTICLES_SUCCESS'
export const ADMIN_ARTICLES_FAIL = 'ADMIN_ARTICLES_FAIL'

export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST'
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS'
export const DELETE_ARTICLE_RESET = 'DELETE_ARTICLE_RESET'
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL'

export const NEW_ARTICLE_REQUEST = 'NEW_ARTICLE_REQUEST'
export const NEW_ARTICLE_SUCCESS = 'NEW_ARTICLE_SUCCESS'
export const NEW_ARTICLE_RESET = 'NEW_ARTICLE_RESET'
export const NEW_ARTICLE_FAIL = 'NEW_ARTICLE_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'