export const BOOKING_REQUEST = 'BOOKING_REQUEST'
export const BOOKING_SUCCESS = 'BOOKING_SUCCESS'
export const BOOKING_FAIL = 'BOOKING_FAIL'

export const ONGOING_BOOKING_REQUEST = 'ONGOING_BOOKING_REQUEST'
export const ONGOING_BOOKING_SUCCESS = 'ONGOING_BOOKING_SUCCESS'
export const ONGOING_BOOKING_FAIL = 'ONGOING_BOOKING_FAIL'

export const ONGOING_SINGLE_BOOKING_REQUEST = 'ONGOING_SINGLE_BOOKING_REQUEST'
export const ONGOING_SINGLE_BOOKING_SUCCESS = 'ONGOING_SINGLE_BOOKING_SUCCESS'
export const ONGOING_SINGLE_BOOKING_FAIL = 'ONGOING_SINGLE_BOOKING_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'