export const DASHBOARD_SERVICE_REQUEST = 'DASHBOARD_SERVICE_REQUEST'
export const DASHBOARD_SERVICE_SUCCESS = 'DASHBOARD_SERVICE_SUCCESS'
export const DASHBOARD_SERVICE_FAIL = 'DASHBOARD_SERVICE_FAIL'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'