export const ALL_GARAGES_REQUEST = 'ALL_GARAGES_REQUEST'
export const ALL_GARAGES_SUCCESS = 'ALL_GARAGES_SUCCESS'
export const ALL_GARAGES_FAIL = 'ALL_GARAGES_FAIL'

export const SINGLE_GARAGE_REQUEST = 'SINGLE_GARAGE_REQUEST'
export const SINGLE_GARAGE_SUCCESS = 'SINGLE_GARAGE_SUCCESS'
export const SINGLE_GARAGE_FAIL = 'SINGLE_GARAGE_FAIL'

export const GET_SERVICE_PACKAGE_REQUEST = 'GET_SERVICE_PACKAGE_REQUEST'
export const GET_SERVICE_PACKAGE_SUCCESS = 'GET_SERVICE_PACKAGE_SUCCESS'
export const GET_SERVICE_PACKAGE_FAIL = 'GET_SERVICE_PACKAGE_FAIL'

export const ALL_OUTLET_REQUEST = 'ALL_OUTLET_REQUEST'
export const ALL_OUTLET_SUCCESS = 'ALL_OUTLET_SUCCESS'
export const ALL_OUTLET_FAIL = 'ALL_OUTLET_FAIL'

export const OUTLET_INFO_REQUEST = 'OUTLET_INFO_REQUEST'
export const OUTLET_INFO_SUCCESS = 'OUTLET_INFO_SUCCESS'
export const OUTLET_INFO_FAIL = 'OUTLET_INFO_FAIL'

export const ADD_OUTLET_REQUEST = 'ADD_OUTLET_REQUEST'
export const ADD_OUTLET_SUCCESS = 'ADD_OUTLET_SUCCESS'
export const ADD_OUTLET_FAIL = 'ADD_OUTLET_FAIL'
export const ADD_OUTLET_RESET = 'ADD_OUTLET_RESET'

export const ADD_PARTNER_STEP_1_REQUEST = 'ADD_PARTNER_STEP_1_REQUEST'
export const ADD_PARTNER_STEP_1_SUCCESS = 'ADD_PARTNER_STEP_1_SUCCESS'
export const ADD_PARTNER_STEP_1_FAIL = 'ADD_PARTNER_STEP_1__FAIL'
export const ADD_PARTNER_STEP_1_RESET = 'ADD_PARTNER_STEP_1_RESET'

export const ADD_MANAGER_REQUEST = 'ADD_MANAGER_REQUEST'
export const ADD_MANAGER_SUCCESS = 'ADD_MANAGER_SUCCESS'
export const ADD_MANAGER_FAIL = 'ADD_MANAGER__FAIL'
export const ADD_MANAGER_RESET = 'ADD_MANAGER_RESET'

export const DELETE_MANAGER_REQUEST = 'DELETE_MANAGER_REQUEST'
export const DELETE_MANAGER_SUCCESS = 'DELETE_MANAGER_SUCCESS'
export const DELETE_MANAGER_FAIL = 'DELETE_MANAGER__FAIL'

export const ADD_PARTNER_STEP_2_REQUEST = 'ADD_PARTNER_STEP_2_REQUEST'
export const ADD_PARTNER_STEP_2_SUCCESS = 'ADD_PARTNER_STEP_2_SUCCESS'
export const ADD_PARTNER_STEP_2_FAIL = 'ADD_PARTNER_STEP_2__FAIL'
export const ADD_PARTNER_STEP_2_RESET = 'ADD_PARTNER_STEP_2_RESET'

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST'
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS'
export const DELETE_SERVICE_FAIL = 'DELETE_SERVICE__FAIL'
export const DELETE_SERVICE_RESET = 'DELETE_SERVICE_RESET'

export const ADD_PARTNER_STEP_4_REQUEST = 'ADD_PARTNER_STEP_4_REQUEST'
export const ADD_PARTNER_STEP_4_SUCCESS = 'ADD_PARTNER_STEP_4_SUCCESS'
export const ADD_PARTNER_STEP_4_FAIL = 'ADD_PARTNER_STEP_4__FAIL'
export const ADD_PARTNER_STEP_4_RESET = 'ADD_PARTNER_STEP_4_RESET'

export const GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST'
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS'
export const GET_SERVICE_FAIL = 'GET_SERVICE__FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'