export const PROMOTION_OFFER_LISTING_REQUEST = 'PROMOTION_OFFER_LISTING_REQUEST'
export const PROMOTION_OFFER_LISTING_SUCCESS = 'PROMOTION_OFFER_LISTING_SUCCESS'
export const PROMOTION_OFFER_LISTING_FAIL = 'PROMOTION_OFFER_LISTING_FAIL'

export const ADD_PROMOTION_OFFER_REQUEST = 'ADD_PROMOTION_OFFER_REQUEST'
export const ADD_PROMOTION_OFFER_SUCCESS = 'ADD_PROMOTION_OFFER_SUCCESS'
export const ADD_PROMOTION_OFFER_FAIL = 'ADD_PROMOTION_OFFER_FAIL'
export const ADD_PROMOTION_OFFER_RESET = 'ADD_PROMOTION_OFFER_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'