export const ADD_SERVICE_REQUEST = 'ADD_SERVICE_REQUEST'
export const ADD_SERVICE_SUCCESS = 'ADD_SERVICE_SUCCESS'
export const ADD_SERVICE_FAIL = 'ADD_SERVICE_FAIL'
export const ADD_SERVICE_RESET = 'ADD_SERVICE_RESET'

export const GET_SERVICE_REQUEST = 'GET_SERVICE_REQUEST'
export const GET_SERVICE_SUCCESS = 'GET_SERVICE_SUCCESS'
export const GET_SERVICE_FAIL = 'GET_SERVICE_FAIL'
export const GET_SERVICE_RESET = 'GET_SERVICE_RESET'

export const GET_SERVICE_PACKAGE_REQUEST = 'GET_SERVICE_PACKAGE_REQUEST'
export const GET_SERVICE_PACKAGE_SUCCESS = 'GET_SERVICE_PACKAGE_SUCCESS'
export const GET_SERVICE_PACKAGE_FAIL = 'GET_SERVICE_PACKAGE_FAIL'

export const GET_SERVICE_PACKAGE_BY_ID_REQUEST = 'GET_SERVICE_PACKAGE_BY_ID_REQUEST'
export const GET_SERVICE_PACKAGE_BY_ID_SUCCESS = 'GET_SERVICE_PACKAGE_BY_ID_SUCCESS'
export const GET_SERVICE_PACKAGE_BY_ID_FAIL = 'GET_SERVICE_PACKAGE_BY_ID_FAIL'

export const SERVICE_INFO_REQUEST = 'SERVICE_INFO_REQUEST'
export const SERVICE_INFO_SUCCESS = 'SERVICE_INFO_SUCCESS'
export const SERVICE_INFO_FAIL = 'SERVICE_INFO_FAIL'

export const GET_SINGLE_PACKAGE_REQUEST = 'GET_SINGLE_PACKAGE_REQUEST'
export const GET_SINGLE_PACKAGE_SUCCESS = 'GET_SINGLE_PACKAGE_SUCCESS'
export const GET_SINGLE_PACKAGE_FAIL = 'GET_SINGLE_PACKAGE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'