export const GET_FAQS_REQUEST = 'GET_FAQS_REQUEST'
export const GET_FAQS_SUCCESS = 'GET_FAQS_SUCCESS'
export const GET_FAQS_FAIL = 'GET_FAQS_FAIL'

export const ADD_FAQS_REQUEST = 'ADD_FAQS_REQUEST'
export const ADD_FAQS_SUCCESS = 'ADD_FAQS_SUCCESS'
export const ADD_FAQS_FAIL = 'ADD_FAQS_FAIL'
export const ADD_FAQS_RESET = 'ADD_FAQS_RESET'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'
