export const ADMIN_USER_ARTICLE_REQUEST = 'ADMIN_USER_ARTICLE_REQUEST'
export const ADMIN_USER_ARTICLE_SUCCESS = 'ADMIN_USER_ARTICLE_SUCCESS'
export const ADMIN_USER_ARTICLE_FAIL = 'ADMIN_USER_ARTICLE_FAIL'

export const USER_USER_ARTICLE_REQUEST = 'USER_USER_ARTICLE_REQUEST'
export const USER_USER_ARTICLE_SUCCESS = 'USER_USER_ARTICLE_SUCCESS'
export const USER_USER_ARTICLE_FAIL = 'USER_USER_ARTICLE_FAIL'

export const GET_USER_ARTICLE_REQUEST = 'GET_USER_ARTICLE_REQUEST'
export const GET_USER_ARTICLE_SUCCESS = 'GET_USER_ARTICLE_SUCCESS'
export const GET_USER_ARTICLE_FAIL = 'GET_USER_ARTICLE_FAIL'


export const UPDATE_USER_ARTICLE_REQUEST = 'UPDATE_USER_ARTICLE_REQUEST'
export const UPDATE_USER_ARTICLE_SUCCESS = 'UPDATE_USER_ARTICLE_SUCCESS'
export const UPDATE_USER_ARTICLE_RESET = 'UPDATE_USER_ARTICLE_RESET'
export const UPDATE_USER_ARTICLE_FAIL = 'UPDATE_USER_ARTICLE_FAIL'

export const DELETE_USER_ARTICLE_REQUEST = 'DELETE_USER_ARTICLE_REQUEST'
export const DELETE_USER_ARTICLE_SUCCESS = 'DELETE_USER_ARTICLE_SUCCESS'
export const DELETE_USER_ARTICLE_RESET = 'DELETE_USER_ARTICLE_RESET'
export const DELETE_USER_ARTICLE_FAIL = 'DELETE_USER_ARTICLE_FAIL'

export const NEW_USER_ARTICLE_REQUEST = 'NEW_USER_ARTICLE_REQUEST'
export const NEW_USER_ARTICLE_SUCCESS = 'NEW_USER_ARTICLE_SUCCESS'
export const NEW_USER_ARTICLE_RESET = 'NEW_USER_ARTICLE_RESET'
export const NEW_USER_ARTICLE_FAIL = 'NEW_USER_ARTICLE_FAIL'

export const CLEAR_ERRORS = 'CLEAR_ERRORS'